import { normalizeHeroSettings } from "@/lib/cms/hero-settings";
import type { CmsHeroSettings } from "@/lib/cms/types";
import type { ExperienceItem } from "@/data/types";

export function buildExperienceDetailHero(item: ExperienceItem): CmsHeroSettings {
  return normalizeHeroSettings({
    heroVariant: item.heroVariant ?? "text",
    heroTitle: item.heroTitle,
    heroSubtitle: item.heroSubtitle ?? item.subtitle ?? "",
    heroPresentationText: item.heroPresentationText ?? "",
    heroPresentationSubtitle: item.heroPresentationSubtitle ?? "",
    heroPresentationTextTypography: item.heroPresentationTextTypography,
    heroPresentationSubtitleTypography: item.heroPresentationSubtitleTypography,
    heroPresentationTextColor: item.heroPresentationTextColor ?? "#FFFFFF",
    heroPresentationImage: item.heroPresentationImage ?? "",
    heroPresentationCtaEnabled: item.heroPresentationCtaEnabled ?? false,
    heroPresentationCtaLabel: item.heroPresentationCtaLabel ?? "Descubrir",
    heroPresentationCtaHref: item.heroPresentationCtaHref ?? "",
    heroPresentationCtaNewTab: item.heroPresentationCtaNewTab ?? false,
    heroPresentationCtaBackgroundColor: item.heroPresentationCtaBackgroundColor ?? "#FFFFFF",
    heroPresentationCtaTextColor: item.heroPresentationCtaTextColor ?? "#3f3933",
    heroMenuTone: item.heroMenuTone,
    heroMenuColor: item.heroMenuColor,
    heroMenuScale: item.heroMenuScale ?? 1,
    heroLogoPositionX: item.heroLogoPositionX,
    heroLogoPositionY: item.heroLogoPositionY,
    heroLogoWidth: item.heroLogoWidth,
    heroLogoTabletPositionX: item.heroLogoTabletPositionX,
    heroLogoTabletPositionY: item.heroLogoTabletPositionY,
    heroLogoTabletWidth: item.heroLogoTabletWidth,
    heroLogoMobilePositionX: item.heroLogoMobilePositionX,
    heroLogoMobilePositionY: item.heroLogoMobilePositionY,
    heroLogoMobileWidth: item.heroLogoMobileWidth,
    heroMenuPositionY: item.heroMenuPositionY,
    heroMenuTabletPositionY: item.heroMenuTabletPositionY,
    heroMenuMobilePositionY: item.heroMenuMobilePositionY,
    heroImage: item.heroImage,
    heroImageMobile: item.heroImageMobile ?? "",
    titleImage: item.heroTitleImage ?? "",
    titleImageSecondary: item.heroTitleImageSecondary ?? "",
    titleImageScale: item.titleImageScale,
    titleImageScaleTablet: item.titleImageScaleTablet,
    titleImageScaleMobile: item.titleImageScaleMobile,
    titleImagePositionX: item.titleImagePositionX,
    titleImagePositionY: item.titleImagePositionY,
    titleImagePositionXTablet: item.titleImagePositionXTablet,
    titleImagePositionYTablet: item.titleImagePositionYTablet,
    titleImagePositionXMobile: item.titleImagePositionXMobile,
    titleImagePositionYMobile: item.titleImagePositionYMobile,
    titleImageSecondaryScale: item.titleImageSecondaryScale,
    titleImageSecondaryScaleTablet: item.titleImageSecondaryScaleTablet,
    titleImageSecondaryScaleMobile: item.titleImageSecondaryScaleMobile,
    titleImageSecondaryPositionX: item.titleImageSecondaryPositionX,
    titleImageSecondaryPositionY: item.titleImageSecondaryPositionY,
    titleImageSecondaryPositionXTablet: item.titleImageSecondaryPositionXTablet,
    titleImageSecondaryPositionYTablet: item.titleImageSecondaryPositionYTablet,
    titleImageSecondaryPositionXMobile: item.titleImageSecondaryPositionXMobile,
    titleImageSecondaryPositionYMobile: item.titleImageSecondaryPositionYMobile,
    heroTitlePositionX: item.heroTitlePositionX,
    heroTitlePositionXTablet: item.heroTitlePositionXTablet,
    heroTitlePositionXMobile: item.heroTitlePositionXMobile,
    heroTitlePositionY: item.heroTitlePositionY,
    heroTitlePositionYTablet: item.heroTitlePositionYTablet,
    heroTitlePositionYMobile: item.heroTitlePositionYMobile,
    heroTitleScale: item.heroTitleScale,
    heroTitleScaleTablet: item.heroTitleScaleTablet,
    heroTitleScaleMobile: item.heroTitleScaleMobile,
    presentationTextPositionX: item.presentationTextPositionX,
    presentationTextPositionY: item.presentationTextPositionY,
    presentationTextPositionXTablet: item.presentationTextPositionXTablet,
    presentationTextPositionYTablet: item.presentationTextPositionYTablet,
    presentationTextPositionXMobile: item.presentationTextPositionXMobile,
    presentationTextPositionYMobile: item.presentationTextPositionYMobile,
    presentationTextScale: item.presentationTextScale,
    presentationTextScaleTablet: item.presentationTextScaleTablet,
    presentationTextScaleMobile: item.presentationTextScaleMobile,
    presentationImagePositionX: item.presentationImagePositionX,
    presentationImagePositionY: item.presentationImagePositionY,
    presentationImagePositionXTablet: item.presentationImagePositionXTablet,
    presentationImagePositionYTablet: item.presentationImagePositionYTablet,
    presentationImagePositionXMobile: item.presentationImagePositionXMobile,
    presentationImagePositionYMobile: item.presentationImagePositionYMobile,
    presentationImageScale: item.presentationImageScale,
    presentationImageScaleTablet: item.presentationImageScaleTablet,
    presentationImageScaleMobile: item.presentationImageScaleMobile,
  });
}
